# Generated by Django 4.1.3 on 2023-01-14 23:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Queseriademisinti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra_venta',
            name='pedido_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Queseriademisinti.pedido'),
        ),
        migrations.AlterField(
            model_name='quejas',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])\\d{5}$', 'Carnet invalido')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tfno',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^\\+53\\d{8}$', 'Teléfono invalido')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Cambio', max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-záãäéëêíîóöúüñç]{3,}(\\s[A-Za-záãäéëêíîóöúüñç]{3,})?(\\s[A-Za-záãäéëêíîóöúüñç]{3,})?$', 'Solo Letras,Introduzca Nombre y dos apellidos')]),
        ),
    ]
